package main

import "testing"

func TestDaemonListenConfigWorkflow(t *testing.T) {
	testDaemonListenConfigWorkflow(t)
}

func TestIntegrationDaemonListenConfigWorkflow(t *testing.T) {
	testDaemonListenConfigWorkflow(t)
}

func TestE2EDaemonListenConfigWorkflow(t *testing.T) {
	testDaemonListenConfigWorkflow(t)
}

func testDaemonListenConfigWorkflow(t *testing.T) {
	t.Helper()
	t.Run("defaults to socket only config", testNewDaemonAppDefaultsToSocketOnlyConfig)
	t.Run("builds handler without listening", testNewDaemonAppBuildsHandlerWithoutListening)
	t.Run("registers core routes", testDaemonAppRegistersCoreRoutes)
	t.Run("does not register static web routes", testDaemonAppDoesNotRegisterStaticWebRoutes)
	t.Run("starts background once", testDaemonAppStartsBackgroundOnce)
	t.Run("serves unix socket and optional tcp", testDaemonAppServesUnixSocketAndOptionalTCP)
	t.Run("cleans stale unix socket", testDaemonAppCleansStaleUnixSocket)
	t.Run("reports tcp port conflict", testDaemonAppReportsTCPPortConflict)
	t.Run("reports uncreatable unix socket path", testDaemonAppReportsUncreatableUnixSocketPath)
	t.Run("cli client config priority", testCLIClientConfigPriority)
	t.Run("status command uses host flag before environment", testStatusCommandUsesHostFlagBeforeEnvironment)
	t.Run("status command uses environment host", testStatusCommandUsesEnvironmentHost)
	t.Run("status command uses default unix socket", testStatusCommandUsesDefaultUnixSocket)
	t.Run("status command reports unreadable daemon", testStatusCommandReportsUnreadableDaemon)
	t.Run("cli list projects classifies errors", TestIntegrationCLIListProjectsClassifiesNotFoundAndUnsupported)
	t.Run("cli list projects text verbose and json", TestIntegrationCLIListProjectsTextVerboseAndJSON)
	t.Run("cli list projects pagination flags", TestIntegrationCLIListProjectsPaginationFlags)
	t.Run("cli up applies project first repeated modified and json", testCLIUpAppliesProjectFirstRepeatedModifiedAndJSON)
	t.Run("cli up applies scheduler script and ps json", TestIntegrationCLIUpAppliesInlineSchedulerScriptAndPSJSON)
	t.Run("cli down first repeated partial and json", testCLIDownFirstRepeatedPartialAndJSON)
	t.Run("cli run streams output and supports session reuse", TestIntegrationCLIRunStreamsOutputAndSupportsSessionReuse)
	t.Run("cli run detach starts background run", TestIntegrationCLIRunDetachStartsBackgroundRun)
	t.Run("cli run detach json", TestIntegrationCLIRunDetachJSON)
	t.Run("cli run detach command logs follow", TestIntegrationCLIRunDetachCommandCanBeFollowedByLogs)
	t.Run("cli run sends jupyter expose", TestIntegrationCLIRunSendsJupyterExpose)
	t.Run("cli run command streams output", TestIntegrationCLIRunCommandSendsCommandAndStreamsOutput)
	t.Run("cli run interactive prompt reuses session", TestIntegrationCLIRunInteractivePromptReusesSession)
	t.Run("cli run interactive command reuses session", TestIntegrationCLIRunInteractiveCommandReusesSession)
	t.Run("cli run interactive removes created sandbox", TestIntegrationCLIRunInteractiveRemoveCreatedSandboxOnExit)
	t.Run("cli run interactive skips existing sandbox remove", TestIntegrationCLIRunInteractiveRemoveSkipsExistingSandbox)
	t.Run("cli run interactive default provider allowed", TestIntegrationCLIRunInteractivePromptDefaultProviderAllowed)
	t.Run("cli run trigger", TestIntegrationCLIRunTrigger)
	t.Run("cli run trigger warnings", TestIntegrationCLIRunTriggerWarnings)
	t.Run("cli run failure returns stable exit code", TestIntegrationCLIRunFailureReturnsStableExitCode)
	t.Run("cli run remove sandbox on success", TestIntegrationCLIRunRemoveSandboxOnSuccess)
	t.Run("cli run remove sandbox json", TestIntegrationCLIRunRemoveSandboxJSONDoesNotPrintCleanupText)
	t.Run("cli run remove sandbox skips failed run", TestIntegrationCLIRunRemoveSandboxSkipsFailedRun)
	t.Run("cli run remove sandbox error", TestIntegrationCLIRunRemoveSandboxError)
	t.Run("cli logs filters run agent session and json", TestIntegrationCLILogsFiltersRunAgentSessionAndJSON)
	t.Run("cli logs tail text json and run id", TestIntegrationCLILogsTailTextJSONAndRunID)
	t.Run("cli logs timestamp and multi run prefixes", TestIntegrationCLILogsTimestampAndMultiRunPrefixes)
	t.Run("cli logs follow uses server stream", TestIntegrationCLILogsFollowUsesServerStream)
	t.Run("cli ps table and json", TestIntegrationCLIPSTableAndJSON)
	t.Run("cli stop sandbox", TestIntegrationCLIStopSandbox)
	t.Run("cli resume sandboxes json", TestIntegrationCLIResumeSandboxesJSON)
	t.Run("cli stats table and json", TestIntegrationCLIStatsTableAndJSON)
	t.Run("cli stats unsupported exit", TestCLIStatsUnsupportedUsesUnsupportedExitCode)
	t.Run("cli remove sandboxes", TestIntegrationCLIRemoveSandboxes)
	t.Run("cli remove sandbox running requires force", TestCLIRemoveSandboxRunningRequiresForce)
	t.Run("cli remove sandbox usage errors", TestCLIRemoveSandboxUsageErrors)
	t.Run("cli stop requires sandbox", TestCLIStopRequiresSandboxUsageError)
	t.Run("cli resume rejects empty sandbox", TestCLIResumeRejectsEmptySandboxUsageError)
	t.Run("cli exec streams and json", TestIntegrationCLIExecStreamsAndSupportsJSON)
	t.Run("cli exec interactive reserved unsupported", TestCLIExecInteractiveReservedUnsupported)
	t.Run("cli exec rejects empty sandbox", TestCLIExecRejectsEmptySandboxUsageError)
	t.Run("cli exec ambiguous session is usage error", TestIntegrationCLIExecAmbiguousSessionIsUsageError)
	t.Run("cli inspect project agent run session json", TestIntegrationCLIInspectProjectAgentRunSandboxSessionJSON)
	t.Run("cli images aliases and json", TestIntegrationCLIImagesAliasesAndJSON)
	t.Run("cli image pull aliases and json", TestIntegrationCLIImagePullAliasesAndJSON)
	t.Run("cli image pull skipped warnings", TestIntegrationCLIImagePullSkippedWarnings)
	t.Run("cli pull project images", TestIntegrationCLIPullProjectImages)
	t.Run("cli pull project images json", TestIntegrationCLIPullProjectImagesJSON)
	t.Run("cli image remove aliases and json", TestIntegrationCLIImageRemoveAliasesAndJSON)
	t.Run("cli image inspect json", TestIntegrationCLIImageInspectJSON)
	t.Run("cli images json accepts OCI store status", TestIntegrationCLIImagesJSONAcceptsOCIStoreStatus)
	t.Run("cli image Docker error is clear", TestIntegrationCLIImageDockerErrorIsClear)
	t.Run("cli image root command warns deprecated", TestCLIImageRootCommandWarnsDeprecated)
}
