package projects

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"agent-compose/pkg/agentcompose/domain"
	"agent-compose/pkg/agentcompose/loaders"
	"agent-compose/pkg/compose"
)

func ManagedLoaderTriggersAndScript(projectID, agentName, schedulerName string, scheduler *compose.NormalizedSchedulerSpec) ([]domain.LoaderTrigger, string, error) {
	if scheduler == nil {
		return nil, "", fmt.Errorf("scheduler is required")
	}
	triggers := make([]domain.LoaderTrigger, 0, len(scheduler.Triggers))
	seenNames := make(map[string]struct{}, len(scheduler.Triggers))
	var script strings.Builder
	script.WriteString("// Generated by agent-compose project scheduler reconcile.\n")
	for i, trigger := range scheduler.Triggers {
		name := strings.TrimSpace(trigger.Name)
		if name != "" {
			if _, ok := seenNames[name]; ok {
				return nil, "", fmt.Errorf("duplicate scheduler trigger name %q", name)
			}
			seenNames[name] = struct{}{}
		}
		id, err := domain.StableManagedTriggerID(projectID, agentName, schedulerName, name, i)
		if err != nil {
			return nil, "", err
		}
		loaderTrigger, registration, err := ManagedLoaderTriggerAndRegistration(id, agentName, trigger)
		if err != nil {
			return nil, "", err
		}
		triggers = append(triggers, loaderTrigger)
		script.WriteString(registration)
	}
	if len(triggers) == 0 {
		script.WriteString("function main() { return { status: \"idle\" }; }\n")
	}
	return triggers, script.String(), nil
}

func ManagedLoaderTriggerAndRegistration(id, agentName string, trigger compose.NormalizedTriggerSpec) (domain.LoaderTrigger, string, error) {
	prompt := strings.TrimSpace(trigger.Prompt)
	if prompt == "" {
		prompt = fmt.Sprintf("Run agent %s.", agentName)
	}
	callback := fmt.Sprintf("async function(event) { return scheduler.agent(%s); }", JSStringLiteral(prompt))
	switch trigger.Kind {
	case "cron":
		specJSON, err := loaders.LoaderCronSpecJSON(trigger.Cron, "")
		if err != nil {
			return domain.LoaderTrigger{}, "", err
		}
		return domain.LoaderTrigger{
			ID:       id,
			Kind:     domain.LoaderTriggerKindCron,
			Enabled:  true,
			SpecJSON: specJSON,
		}, fmt.Sprintf("scheduler.cron(%s, %s, %s);\n", JSStringLiteral(id), JSStringLiteral(trigger.Cron), callback), nil
	case "interval":
		interval, err := time.ParseDuration(trigger.Interval)
		if err != nil {
			return domain.LoaderTrigger{}, "", err
		}
		intervalMs := interval.Milliseconds()
		if intervalMs <= 0 {
			return domain.LoaderTrigger{}, "", fmt.Errorf("interval trigger %s must be at least 1ms", id)
		}
		specJSON, err := domain.MarshalJSONCompact(map[string]any{"kind": domain.LoaderTriggerKindInterval, "interval": trigger.Interval})
		if err != nil {
			return domain.LoaderTrigger{}, "", err
		}
		return domain.LoaderTrigger{
			ID:         id,
			Kind:       domain.LoaderTriggerKindInterval,
			IntervalMs: intervalMs,
			Enabled:    true,
			SpecJSON:   specJSON,
		}, fmt.Sprintf("scheduler.interval(%s, %s, %d);\n", JSStringLiteral(id), callback, intervalMs), nil
	case "timeout":
		delay, err := time.ParseDuration(trigger.Timeout)
		if err != nil {
			return domain.LoaderTrigger{}, "", err
		}
		delayMs := delay.Milliseconds()
		if delayMs <= 0 {
			return domain.LoaderTrigger{}, "", fmt.Errorf("timeout trigger %s must be at least 1ms", id)
		}
		specJSON, err := domain.MarshalJSONCompact(map[string]any{"kind": domain.LoaderTriggerKindTimeout, "timeout": trigger.Timeout})
		if err != nil {
			return domain.LoaderTrigger{}, "", err
		}
		return domain.LoaderTrigger{
			ID:         id,
			Kind:       domain.LoaderTriggerKindTimeout,
			IntervalMs: delayMs,
			Enabled:    true,
			SpecJSON:   specJSON,
		}, fmt.Sprintf("scheduler.timeout(%s, %s, %d);\n", JSStringLiteral(id), callback, delayMs), nil
	case "event":
		if trigger.Event == nil {
			return domain.LoaderTrigger{}, "", fmt.Errorf("event trigger topic is required")
		}
		topic := strings.TrimSpace(trigger.Event.Topic)
		specJSON, err := domain.MarshalJSONCompact(map[string]any{"kind": domain.LoaderTriggerKindEvent, "topic": topic})
		if err != nil {
			return domain.LoaderTrigger{}, "", err
		}
		return domain.LoaderTrigger{
			ID:       id,
			Kind:     domain.LoaderTriggerKindEvent,
			Topic:    topic,
			Enabled:  true,
			SpecJSON: specJSON,
		}, fmt.Sprintf("scheduler.on(%s, %s, %s);\n", JSStringLiteral(topic), JSStringLiteral(id), callback), nil
	default:
		return domain.LoaderTrigger{}, "", fmt.Errorf("unsupported scheduler trigger kind %q", trigger.Kind)
	}
}

func JSStringLiteral(value string) string {
	data, err := json.Marshal(value)
	if err != nil {
		return `""`
	}
	return string(data)
}
