package driver

import "testing"

func TestRuntimeDriverWorkflow(t *testing.T) {
	TestDockerRuntimeSessionProxyStateUsesContainerNameAndGuestPort(t)
	TestPrepareRuntimeMountManifestForDockerIncludesRequiredMountsOnly(t)
	TestPrepareRuntimeMountManifestCreatesSourcesAndWritesFile(t)
	TestPrepareRuntimeMountManifestForDirectoryOnlyDriversMountsSingleSessionDirectory(t)
	testRuntimeMountManifestDriverSpecificStartPreparationWorkflow(t)
	testDockerImageRefMatchingInternals(t)
	testConsumeDockerPullStream(t)
	testExecOutputFilterWorkflows(t)
	testJupyterGuestCoverageWorkflow(t)
}

func TestIntegrationRuntimeDriverWorkflow(t *testing.T) {
	TestDockerRuntimeSessionProxyStateUsesContainerNameAndGuestPort(t)
	TestPrepareRuntimeMountManifestForDockerIncludesRequiredMountsOnly(t)
	TestPrepareRuntimeMountManifestCreatesSourcesAndWritesFile(t)
	TestPrepareRuntimeMountManifestForDirectoryOnlyDriversMountsSingleSessionDirectory(t)
	testRuntimeMountManifestDriverSpecificStartPreparationWorkflow(t)
	testDockerImageRefMatchingInternals(t)
	testConsumeDockerPullStream(t)
	testExecOutputFilterWorkflows(t)
	testJupyterGuestCoverageWorkflow(t)
}

func TestE2ERuntimeDriverWorkflow(t *testing.T) {
	TestDockerRuntimeSessionProxyStateUsesContainerNameAndGuestPort(t)
	TestPrepareRuntimeMountManifestForDockerIncludesRequiredMountsOnly(t)
	TestPrepareRuntimeMountManifestCreatesSourcesAndWritesFile(t)
	TestPrepareRuntimeMountManifestForDirectoryOnlyDriversMountsSingleSessionDirectory(t)
	testRuntimeMountManifestDriverSpecificStartPreparationWorkflow(t)
	testDockerImageRefMatchingInternals(t)
	testConsumeDockerPullStream(t)
	testExecOutputFilterWorkflows(t)
	testJupyterGuestCoverageWorkflow(t)
}
