// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: health/v1/health.proto

package healthv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemoryUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alloc         uint64                 `protobuf:"varint,1,opt,name=alloc,proto3" json:"alloc,omitempty"`
	TotalAlloc    uint64                 `protobuf:"varint,2,opt,name=total_alloc,json=totalAlloc,proto3" json:"total_alloc,omitempty"`
	Sys           uint64                 `protobuf:"varint,3,opt,name=sys,proto3" json:"sys,omitempty"`
	NumGc         uint32                 `protobuf:"varint,4,opt,name=num_gc,json=numGc,proto3" json:"num_gc,omitempty"`
	HeapAlloc     uint64                 `protobuf:"varint,5,opt,name=heap_alloc,json=heapAlloc,proto3" json:"heap_alloc,omitempty"`
	HeapInuse     uint64                 `protobuf:"varint,6,opt,name=heap_inuse,json=heapInuse,proto3" json:"heap_inuse,omitempty"`
	HeapSys       uint64                 `protobuf:"varint,7,opt,name=heap_sys,json=heapSys,proto3" json:"heap_sys,omitempty"`
	HeapIdle      uint64                 `protobuf:"varint,8,opt,name=heap_idle,json=heapIdle,proto3" json:"heap_idle,omitempty"`
	StackInuse    uint64                 `protobuf:"varint,9,opt,name=stack_inuse,json=stackInuse,proto3" json:"stack_inuse,omitempty"`
	StackSys      uint64                 `protobuf:"varint,10,opt,name=stack_sys,json=stackSys,proto3" json:"stack_sys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryUsage) Reset() {
	*x = MemoryUsage{}
	mi := &file_health_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryUsage) ProtoMessage() {}

func (x *MemoryUsage) ProtoReflect() protoreflect.Message {
	mi := &file_health_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryUsage.ProtoReflect.Descriptor instead.
func (*MemoryUsage) Descriptor() ([]byte, []int) {
	return file_health_v1_health_proto_rawDescGZIP(), []int{0}
}

func (x *MemoryUsage) GetAlloc() uint64 {
	if x != nil {
		return x.Alloc
	}
	return 0
}

func (x *MemoryUsage) GetTotalAlloc() uint64 {
	if x != nil {
		return x.TotalAlloc
	}
	return 0
}

func (x *MemoryUsage) GetSys() uint64 {
	if x != nil {
		return x.Sys
	}
	return 0
}

func (x *MemoryUsage) GetNumGc() uint32 {
	if x != nil {
		return x.NumGc
	}
	return 0
}

func (x *MemoryUsage) GetHeapAlloc() uint64 {
	if x != nil {
		return x.HeapAlloc
	}
	return 0
}

func (x *MemoryUsage) GetHeapInuse() uint64 {
	if x != nil {
		return x.HeapInuse
	}
	return 0
}

func (x *MemoryUsage) GetHeapSys() uint64 {
	if x != nil {
		return x.HeapSys
	}
	return 0
}

func (x *MemoryUsage) GetHeapIdle() uint64 {
	if x != nil {
		return x.HeapIdle
	}
	return 0
}

func (x *MemoryUsage) GetStackInuse() uint64 {
	if x != nil {
		return x.StackInuse
	}
	return 0
}

func (x *MemoryUsage) GetStackSys() uint64 {
	if x != nil {
		return x.StackSys
	}
	return 0
}

type HealthStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	CurrentTime   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UptimeSeconds uint64                 `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	GoVersion     string                 `protobuf:"bytes,5,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	NumGoroutines uint64                 `protobuf:"varint,6,opt,name=num_goroutines,json=numGoroutines,proto3" json:"num_goroutines,omitempty"`
	Memory        *MemoryUsage           `protobuf:"bytes,7,opt,name=memory,proto3" json:"memory,omitempty"`
	BuildVersion  string                 `protobuf:"bytes,8,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	Process       *ProcessUsage          `protobuf:"bytes,9,opt,name=process,proto3" json:"process,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatusResponse) Reset() {
	*x = HealthStatusResponse{}
	mi := &file_health_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatusResponse) ProtoMessage() {}

func (x *HealthStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatusResponse.ProtoReflect.Descriptor instead.
func (*HealthStatusResponse) Descriptor() ([]byte, []int) {
	return file_health_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthStatusResponse) GetCurrentTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentTime
	}
	return nil
}

func (x *HealthStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *HealthStatusResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthStatusResponse) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *HealthStatusResponse) GetNumGoroutines() uint64 {
	if x != nil {
		return x.NumGoroutines
	}
	return 0
}

func (x *HealthStatusResponse) GetMemory() *MemoryUsage {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *HealthStatusResponse) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

func (x *HealthStatusResponse) GetProcess() *ProcessUsage {
	if x != nil {
		return x.Process
	}
	return nil
}

type ProcessUsage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent      float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	CpuUserMillis   uint64                 `protobuf:"varint,2,opt,name=cpu_user_millis,json=cpuUserMillis,proto3" json:"cpu_user_millis,omitempty"`
	CpuSystemMillis uint64                 `protobuf:"varint,3,opt,name=cpu_system_millis,json=cpuSystemMillis,proto3" json:"cpu_system_millis,omitempty"`
	RssBytes        uint64                 `protobuf:"varint,4,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	ReadBytes       uint64                 `protobuf:"varint,5,opt,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`
	WriteBytes      uint64                 `protobuf:"varint,6,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`
	ReadOps         uint64                 `protobuf:"varint,7,opt,name=read_ops,json=readOps,proto3" json:"read_ops,omitempty"`
	WriteOps        uint64                 `protobuf:"varint,8,opt,name=write_ops,json=writeOps,proto3" json:"write_ops,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessUsage) Reset() {
	*x = ProcessUsage{}
	mi := &file_health_v1_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessUsage) ProtoMessage() {}

func (x *ProcessUsage) ProtoReflect() protoreflect.Message {
	mi := &file_health_v1_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessUsage.ProtoReflect.Descriptor instead.
func (*ProcessUsage) Descriptor() ([]byte, []int) {
	return file_health_v1_health_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessUsage) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessUsage) GetCpuUserMillis() uint64 {
	if x != nil {
		return x.CpuUserMillis
	}
	return 0
}

func (x *ProcessUsage) GetCpuSystemMillis() uint64 {
	if x != nil {
		return x.CpuSystemMillis
	}
	return 0
}

func (x *ProcessUsage) GetRssBytes() uint64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

func (x *ProcessUsage) GetReadBytes() uint64 {
	if x != nil {
		return x.ReadBytes
	}
	return 0
}

func (x *ProcessUsage) GetWriteBytes() uint64 {
	if x != nil {
		return x.WriteBytes
	}
	return 0
}

func (x *ProcessUsage) GetReadOps() uint64 {
	if x != nil {
		return x.ReadOps
	}
	return 0
}

func (x *ProcessUsage) GetWriteOps() uint64 {
	if x != nil {
		return x.WriteOps
	}
	return 0
}

var File_health_v1_health_proto protoreflect.FileDescriptor

const file_health_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x16health/v1/health.proto\x12\thealth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa1\x02\n" +
	"\vMemoryUsage\x12\x14\n" +
	"\x05alloc\x18\x01 \x01(\x04R\x05alloc\x12\x1f\n" +
	"\vtotal_alloc\x18\x02 \x01(\x04R\n" +
	"totalAlloc\x12\x10\n" +
	"\x03sys\x18\x03 \x01(\x04R\x03sys\x12\x15\n" +
	"\x06num_gc\x18\x04 \x01(\rR\x05numGc\x12\x1d\n" +
	"\n" +
	"heap_alloc\x18\x05 \x01(\x04R\theapAlloc\x12\x1d\n" +
	"\n" +
	"heap_inuse\x18\x06 \x01(\x04R\theapInuse\x12\x19\n" +
	"\bheap_sys\x18\a \x01(\x04R\aheapSys\x12\x1b\n" +
	"\theap_idle\x18\b \x01(\x04R\bheapIdle\x12\x1f\n" +
	"\vstack_inuse\x18\t \x01(\x04R\n" +
	"stackInuse\x12\x1b\n" +
	"\tstack_sys\x18\n" +
	" \x01(\x04R\bstackSys\"\x9f\x03\n" +
	"\x14HealthStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12=\n" +
	"\fcurrent_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vcurrentTime\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x04R\ruptimeSeconds\x12\x1d\n" +
	"\n" +
	"go_version\x18\x05 \x01(\tR\tgoVersion\x12%\n" +
	"\x0enum_goroutines\x18\x06 \x01(\x04R\rnumGoroutines\x12.\n" +
	"\x06memory\x18\a \x01(\v2\x16.health.v1.MemoryUsageR\x06memory\x12#\n" +
	"\rbuild_version\x18\b \x01(\tR\fbuildVersion\x121\n" +
	"\aprocess\x18\t \x01(\v2\x17.health.v1.ProcessUsageR\aprocess\"\x98\x02\n" +
	"\fProcessUsage\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12&\n" +
	"\x0fcpu_user_millis\x18\x02 \x01(\x04R\rcpuUserMillis\x12*\n" +
	"\x11cpu_system_millis\x18\x03 \x01(\x04R\x0fcpuSystemMillis\x12\x1b\n" +
	"\trss_bytes\x18\x04 \x01(\x04R\brssBytes\x12\x1d\n" +
	"\n" +
	"read_bytes\x18\x05 \x01(\x04R\treadBytes\x12\x1f\n" +
	"\vwrite_bytes\x18\x06 \x01(\x04R\n" +
	"writeBytes\x12\x19\n" +
	"\bread_ops\x18\a \x01(\x04R\areadOps\x12\x1b\n" +
	"\twrite_ops\x18\b \x01(\x04R\bwriteOps2\x9c\x01\n" +
	"\rHealthService\x12A\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a\x1f.health.v1.HealthStatusResponse\x12H\n" +
	"\vWatchStatus\x12\x16.google.protobuf.Empty\x1a\x1f.health.v1.HealthStatusResponse0\x01B(Z&agent-compose/proto/health/v1;healthv1b\x06proto3"

var (
	file_health_v1_health_proto_rawDescOnce sync.Once
	file_health_v1_health_proto_rawDescData []byte
)

func file_health_v1_health_proto_rawDescGZIP() []byte {
	file_health_v1_health_proto_rawDescOnce.Do(func() {
		file_health_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_v1_health_proto_rawDesc), len(file_health_v1_health_proto_rawDesc)))
	})
	return file_health_v1_health_proto_rawDescData
}

var file_health_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_health_v1_health_proto_goTypes = []any{
	(*MemoryUsage)(nil),           // 0: health.v1.MemoryUsage
	(*HealthStatusResponse)(nil),  // 1: health.v1.HealthStatusResponse
	(*ProcessUsage)(nil),          // 2: health.v1.ProcessUsage
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_health_v1_health_proto_depIdxs = []int32{
	3, // 0: health.v1.HealthStatusResponse.current_time:type_name -> google.protobuf.Timestamp
	3, // 1: health.v1.HealthStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	0, // 2: health.v1.HealthStatusResponse.memory:type_name -> health.v1.MemoryUsage
	2, // 3: health.v1.HealthStatusResponse.process:type_name -> health.v1.ProcessUsage
	4, // 4: health.v1.HealthService.Status:input_type -> google.protobuf.Empty
	4, // 5: health.v1.HealthService.WatchStatus:input_type -> google.protobuf.Empty
	1, // 6: health.v1.HealthService.Status:output_type -> health.v1.HealthStatusResponse
	1, // 7: health.v1.HealthService.WatchStatus:output_type -> health.v1.HealthStatusResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_health_v1_health_proto_init() }
func file_health_v1_health_proto_init() {
	if File_health_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_v1_health_proto_rawDesc), len(file_health_v1_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_v1_health_proto_goTypes,
		DependencyIndexes: file_health_v1_health_proto_depIdxs,
		MessageInfos:      file_health_v1_health_proto_msgTypes,
	}.Build()
	File_health_v1_health_proto = out.File
	file_health_v1_health_proto_goTypes = nil
	file_health_v1_health_proto_depIdxs = nil
}
