// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: health/v1/health.proto

package healthv1connect

import (
	v1 "agent-compose/proto/health/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HealthServiceName is the fully-qualified name of the HealthService service.
	HealthServiceName = "health.v1.HealthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HealthServiceStatusProcedure is the fully-qualified name of the HealthService's Status RPC.
	HealthServiceStatusProcedure = "/health.v1.HealthService/Status"
	// HealthServiceWatchStatusProcedure is the fully-qualified name of the HealthService's WatchStatus
	// RPC.
	HealthServiceWatchStatusProcedure = "/health.v1.HealthService/WatchStatus"
)

// HealthServiceClient is a client for the health.v1.HealthService service.
type HealthServiceClient interface {
	Status(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.HealthStatusResponse], error)
	WatchStatus(context.Context, *connect.Request[emptypb.Empty]) (*connect.ServerStreamForClient[v1.HealthStatusResponse], error)
}

// NewHealthServiceClient constructs a client for the health.v1.HealthService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHealthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HealthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	healthServiceMethods := v1.File_health_v1_health_proto.Services().ByName("HealthService").Methods()
	return &healthServiceClient{
		status: connect.NewClient[emptypb.Empty, v1.HealthStatusResponse](
			httpClient,
			baseURL+HealthServiceStatusProcedure,
			connect.WithSchema(healthServiceMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
		watchStatus: connect.NewClient[emptypb.Empty, v1.HealthStatusResponse](
			httpClient,
			baseURL+HealthServiceWatchStatusProcedure,
			connect.WithSchema(healthServiceMethods.ByName("WatchStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// healthServiceClient implements HealthServiceClient.
type healthServiceClient struct {
	status      *connect.Client[emptypb.Empty, v1.HealthStatusResponse]
	watchStatus *connect.Client[emptypb.Empty, v1.HealthStatusResponse]
}

// Status calls health.v1.HealthService.Status.
func (c *healthServiceClient) Status(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[v1.HealthStatusResponse], error) {
	return c.status.CallUnary(ctx, req)
}

// WatchStatus calls health.v1.HealthService.WatchStatus.
func (c *healthServiceClient) WatchStatus(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.ServerStreamForClient[v1.HealthStatusResponse], error) {
	return c.watchStatus.CallServerStream(ctx, req)
}

// HealthServiceHandler is an implementation of the health.v1.HealthService service.
type HealthServiceHandler interface {
	Status(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.HealthStatusResponse], error)
	WatchStatus(context.Context, *connect.Request[emptypb.Empty], *connect.ServerStream[v1.HealthStatusResponse]) error
}

// NewHealthServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHealthServiceHandler(svc HealthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	healthServiceMethods := v1.File_health_v1_health_proto.Services().ByName("HealthService").Methods()
	healthServiceStatusHandler := connect.NewUnaryHandler(
		HealthServiceStatusProcedure,
		svc.Status,
		connect.WithSchema(healthServiceMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	healthServiceWatchStatusHandler := connect.NewServerStreamHandler(
		HealthServiceWatchStatusProcedure,
		svc.WatchStatus,
		connect.WithSchema(healthServiceMethods.ByName("WatchStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/health.v1.HealthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HealthServiceStatusProcedure:
			healthServiceStatusHandler.ServeHTTP(w, r)
		case HealthServiceWatchStatusProcedure:
			healthServiceWatchStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHealthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHealthServiceHandler struct{}

func (UnimplementedHealthServiceHandler) Status(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.HealthStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("health.v1.HealthService.Status is not implemented"))
}

func (UnimplementedHealthServiceHandler) WatchStatus(context.Context, *connect.Request[emptypb.Empty], *connect.ServerStream[v1.HealthStatusResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("health.v1.HealthService.WatchStatus is not implemented"))
}
