package compose

import "testing"

func TestIntegrationComposeParseNormalizeAndOutputWorkflows(t *testing.T) {
	t.Run("default project name from compose directory", TestNormalizeDefaultsProjectNameFromComposeDirectory)
	t.Run("default project name from relative path", TestNormalizeDefaultsProjectNameFromRelativeComposePath)
	t.Run("explicit project name wins", TestNormalizeExplicitProjectNameWinsOverDirectory)
	t.Run("project name required", TestNormalizeRequiresProjectNameWithoutDefaultPath)
	t.Run("sort agents", TestNormalizeSortsAgentsForStableOutput)
	t.Run("agent capsets", TestNormalizeAgentCapsetIDs)
	t.Run("valid agent names", TestNormalizePreservesValidAgentNames)
	t.Run("invalid agent name", TestNormalizeRejectsInvalidAgentName)
	t.Run("driver defaults", TestNormalizeDefaultsDriver)
	t.Run("agent model interpolation", TestNormalizeInterpolatesAgentModelFromEnvironment)
	t.Run("missing model environment", TestNormalizeRequiresAgentModelEnvironmentReference)
	t.Run("empty driver", TestNormalizeRejectsEmptyDriver)
	t.Run("multiple drivers", TestNormalizeRejectsMultipleDrivers)
	t.Run("firecracker driver", TestNormalizeRejectsFirecrackerDriver)
	t.Run("supported driver", TestNormalizeAcceptsSupportedDriver)
	t.Run("jupyter config", TestNormalizePreservesJupyterConfig)
	t.Run("jupyter defaults", TestNormalizeDropsDefaultJupyterConfig)
	t.Run("invalid jupyter port", TestNormalizeRejectsInvalidJupyterGuestPort)
	t.Run("invalid trigger", TestNormalizeRejectsInvalidTrigger)
	t.Run("scheduler script", TestNormalizePreservesSchedulerScript)
	t.Run("scheduler script URL snapshot", TestNormalizeResolvesSchedulerScriptURLSnapshot)
	t.Run("scheduler script URL validation", TestNormalizeSchedulerScriptURLValidation)
	t.Run("scheduler script URL content", TestNormalizeRejectsInvalidResolvedSchedulerScriptContent)
	t.Run("blank scheduler script", TestNormalizeTreatsBlankSchedulerScriptAsUnset)
	t.Run("scheduler script with triggers", TestNormalizeRejectsSchedulerScriptWithTriggers)
	t.Run("scheduler script URL with triggers", TestNormalizeRejectsSchedulerScriptURLWithTriggers)
	t.Run("scheduler triggers", TestNormalizePreservesSchedulerTriggersWithoutScript)
	t.Run("invalid trigger payloads", TestNormalizeRejectsInvalidTriggerPayloads)
	t.Run("trigger without kind", TestNormalizeRejectsTriggerWithoutKind)
	t.Run("duplicate agent keys", TestParseRejectsDuplicateAgentKeys)
	t.Run("parse minimal", TestParseMinimalSpec)
	t.Run("parse full", TestParseFullSpec)
	t.Run("parse scheduler script", TestParseSchedulerScript)
	t.Run("parse scheduler script provider", TestParseSchedulerScriptProvider)
	t.Run("parse invalid scheduler script provider", TestParseRejectsInvalidSchedulerScriptProviderObject)
	t.Run("parse unknown field", TestParseUnknownFieldIncludesPath)
	t.Run("parse removed network field", TestParseRejectsRemovedNetworkField)
	t.Run("parse invalid yaml", TestParseInvalidYAML)
	t.Run("parse type error", TestParseTypeErrorIncludesPath)
	t.Run("parse scheduler script type error", TestParseSchedulerScriptTypeErrorIncludesPath)
	t.Run("parse jupyter expose field", TestParseRejectsUnsupportedJupyterExposeFields)
	t.Run("parse jupyter guest port type", TestParseRejectsInvalidJupyterGuestPortType)
	t.Run("parse file", TestParseFileIncludesPath)
	t.Run("env values", TestNormalizeInterpolatesEnvValues)
	t.Run("missing env field path", TestNormalizeInterpolationMissingEnvIncludesFieldPath)
	t.Run("compose variables", TestNormalizeDoesNotInterpolateFromComposeVariables)
	t.Run("redacted output", TestRedactedOutputDoesNotLeakSecretValues)
	t.Run("redacted scheduler script", TestRedactedOutputPreservesSchedulerScript)
	t.Run("canonical scheduler script", TestCanonicalOutputIncludesSchedulerScriptAndIsStable)
	t.Run("canonical capsets", TestCanonicalOutputIncludesAgentCapsetIDs)
	t.Run("canonical jupyter", TestCanonicalOutputIncludesJupyterAndIsStable)
	t.Run("hash field order", TestSpecHashIgnoresFieldAndMapOrder)
	t.Run("hash semantic differences", TestSpecHashIncludesSemanticDifferences)
	t.Run("hash scheduler script", TestSpecHashIncludesSchedulerScriptChanges)
	t.Run("hash scheduler script URL snapshot", TestResolvedSchedulerScriptURLUsesSnapshotForOutputAndHash)
	t.Run("unresolved scheduler script URL", TestUnresolvedSchedulerScriptURLFailsCanonicalOutputAndHash)
	t.Run("script URL files", TestDefaultScriptSourceResolverReadsFilesAndFileURLs)
	t.Run("script URL HTTP failures", TestDefaultScriptSourceResolverHTTPFailures)
	t.Run("script URL HTTP size", TestDefaultScriptSourceResolverLimitsDecodedHTTPContent)
	t.Run("script URL HTTPS downgrade", TestDefaultScriptSourceResolverRejectsHTTPSDowngrade)
	t.Run("hash jupyter", TestSpecHashIncludesJupyterChanges)
	t.Run("hash driver defaults", TestSpecHashNormalizesDriverDefaults)
	t.Run("hash json order", TestSpecHashSupportsJSONInputOrder)
	t.Run("parse mcp", TestParseMCPConfig)
	t.Run("parse invalid mcp ref", TestParseRejectsInvalidMCPRefType)
	t.Run("normalize mcp", TestNormalizeMCPConfig)
	t.Run("normalize invalid mcp ref", TestNormalizeRejectsUndefinedMCPRef)
	t.Run("normalize invalid mcp shape", TestNormalizeRejectsInvalidMCPShape)
	t.Run("redacted mcp", TestRedactedOutputDoesNotLeakMCPSecrets)
}

func TestE2EComposeParseNormalizeAndOutputWorkflows(t *testing.T) {
	TestIntegrationComposeParseNormalizeAndOutputWorkflows(t)
}
