package compose

import "testing"

func TestIntegrationComposeParseNormalizeAndOutputWorkflows(t *testing.T) {
	t.Run("default project name from compose directory", TestNormalizeDefaultsProjectNameFromComposeDirectory)
	t.Run("default project name from relative path", TestNormalizeDefaultsProjectNameFromRelativeComposePath)
	t.Run("explicit project name wins", TestNormalizeExplicitProjectNameWinsOverDirectory)
	t.Run("project name required", TestNormalizeRequiresProjectNameWithoutDefaultPath)
	t.Run("sort agents", TestNormalizeSortsAgentsForStableOutput)
	t.Run("agent capsets", TestNormalizeAgentCapsetIDs)
	t.Run("valid agent names", TestNormalizePreservesValidAgentNames)
	t.Run("invalid agent name", TestNormalizeRejectsInvalidAgentName)
	t.Run("driver and network defaults", TestNormalizeDefaultsDriverAndNetwork)
	t.Run("agent model interpolation", TestNormalizeInterpolatesAgentModelFromEnvironment)
	t.Run("missing model environment", TestNormalizeRequiresAgentModelEnvironmentReference)
	t.Run("empty driver", TestNormalizeRejectsEmptyDriver)
	t.Run("multiple drivers", TestNormalizeRejectsMultipleDrivers)
	t.Run("firecracker driver", TestNormalizeRejectsFirecrackerDriver)
	t.Run("supported driver", TestNormalizeAcceptsSupportedDriverAndDefaultNetwork)
	t.Run("empty network default", TestNormalizeAcceptsEmptyNetworkAsDefault)
	t.Run("jupyter config", TestNormalizePreservesJupyterConfig)
	t.Run("jupyter defaults", TestNormalizeDropsDefaultJupyterConfig)
	t.Run("invalid jupyter port", TestNormalizeRejectsInvalidJupyterGuestPort)
	t.Run("unsupported network", TestNormalizeRejectsUnsupportedNetwork)
	t.Run("invalid trigger", TestNormalizeRejectsInvalidTrigger)
	t.Run("scheduler script", TestNormalizePreservesSchedulerScript)
	t.Run("blank scheduler script", TestNormalizeTreatsBlankSchedulerScriptAsUnset)
	t.Run("scheduler script with triggers", TestNormalizeRejectsSchedulerScriptWithTriggers)
	t.Run("scheduler triggers", TestNormalizePreservesSchedulerTriggersWithoutScript)
	t.Run("invalid trigger payloads", TestNormalizeRejectsInvalidTriggerPayloads)
	t.Run("trigger without kind", TestNormalizeRejectsTriggerWithoutKind)
	t.Run("duplicate agent keys", TestParseRejectsDuplicateAgentKeys)
	t.Run("parse minimal", TestParseMinimalSpec)
	t.Run("parse full", TestParseFullSpec)
	t.Run("parse scheduler script", TestParseSchedulerScript)
	t.Run("parse unknown field", TestParseUnknownFieldIncludesPath)
	t.Run("parse invalid yaml", TestParseInvalidYAML)
	t.Run("parse type error", TestParseTypeErrorIncludesPath)
	t.Run("parse scheduler script type error", TestParseSchedulerScriptTypeErrorIncludesPath)
	t.Run("parse jupyter expose field", TestParseRejectsUnsupportedJupyterExposeFields)
	t.Run("parse jupyter guest port type", TestParseRejectsInvalidJupyterGuestPortType)
	t.Run("parse file", TestParseFileIncludesPath)
	t.Run("env values", TestNormalizeInterpolatesEnvValues)
	t.Run("missing env field path", TestNormalizeInterpolationMissingEnvIncludesFieldPath)
	t.Run("compose variables", TestNormalizeDoesNotInterpolateFromComposeVariables)
	t.Run("redacted output", TestRedactedOutputDoesNotLeakSecretValues)
	t.Run("redacted scheduler script", TestRedactedOutputPreservesSchedulerScript)
	t.Run("canonical scheduler script", TestCanonicalOutputIncludesSchedulerScriptAndIsStable)
	t.Run("canonical capsets", TestCanonicalOutputIncludesAgentCapsetIDs)
	t.Run("canonical jupyter", TestCanonicalOutputIncludesJupyterAndIsStable)
	t.Run("hash field order", TestSpecHashIgnoresFieldAndMapOrder)
	t.Run("hash semantic differences", TestSpecHashIncludesSemanticDifferences)
	t.Run("hash scheduler script", TestSpecHashIncludesSchedulerScriptChanges)
	t.Run("hash jupyter", TestSpecHashIncludesJupyterChanges)
	t.Run("hash defaults", TestSpecHashNormalizesDefaults)
	t.Run("hash json order", TestSpecHashSupportsJSONInputOrder)
}

func TestE2EComposeParseNormalizeAndOutputWorkflows(t *testing.T) {
	TestIntegrationComposeParseNormalizeAndOutputWorkflows(t)
}
