// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/agentcompose/v2/agentcompose.proto

package agentcomposev2connect

import (
	v2 "agent-compose/proto/agentcompose/v2"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProjectServiceName is the fully-qualified name of the ProjectService service.
	ProjectServiceName = "agentcompose.v2.ProjectService"
	// RunServiceName is the fully-qualified name of the RunService service.
	RunServiceName = "agentcompose.v2.RunService"
	// ExecServiceName is the fully-qualified name of the ExecService service.
	ExecServiceName = "agentcompose.v2.ExecService"
	// ImageServiceName is the fully-qualified name of the ImageService service.
	ImageServiceName = "agentcompose.v2.ImageService"
	// SandboxServiceName is the fully-qualified name of the SandboxService service.
	SandboxServiceName = "agentcompose.v2.SandboxService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProjectServiceValidateProjectProcedure is the fully-qualified name of the ProjectService's
	// ValidateProject RPC.
	ProjectServiceValidateProjectProcedure = "/agentcompose.v2.ProjectService/ValidateProject"
	// ProjectServiceApplyProjectProcedure is the fully-qualified name of the ProjectService's
	// ApplyProject RPC.
	ProjectServiceApplyProjectProcedure = "/agentcompose.v2.ProjectService/ApplyProject"
	// ProjectServiceGetProjectProcedure is the fully-qualified name of the ProjectService's GetProject
	// RPC.
	ProjectServiceGetProjectProcedure = "/agentcompose.v2.ProjectService/GetProject"
	// ProjectServiceListProjectsProcedure is the fully-qualified name of the ProjectService's
	// ListProjects RPC.
	ProjectServiceListProjectsProcedure = "/agentcompose.v2.ProjectService/ListProjects"
	// ProjectServiceRemoveProjectProcedure is the fully-qualified name of the ProjectService's
	// RemoveProject RPC.
	ProjectServiceRemoveProjectProcedure = "/agentcompose.v2.ProjectService/RemoveProject"
	// ProjectServiceWatchProjectProcedure is the fully-qualified name of the ProjectService's
	// WatchProject RPC.
	ProjectServiceWatchProjectProcedure = "/agentcompose.v2.ProjectService/WatchProject"
	// RunServiceRunAgentProcedure is the fully-qualified name of the RunService's RunAgent RPC.
	RunServiceRunAgentProcedure = "/agentcompose.v2.RunService/RunAgent"
	// RunServiceStartRunProcedure is the fully-qualified name of the RunService's StartRun RPC.
	RunServiceStartRunProcedure = "/agentcompose.v2.RunService/StartRun"
	// RunServiceRunAgentStreamProcedure is the fully-qualified name of the RunService's RunAgentStream
	// RPC.
	RunServiceRunAgentStreamProcedure = "/agentcompose.v2.RunService/RunAgentStream"
	// RunServiceGetRunProcedure is the fully-qualified name of the RunService's GetRun RPC.
	RunServiceGetRunProcedure = "/agentcompose.v2.RunService/GetRun"
	// RunServiceListRunsProcedure is the fully-qualified name of the RunService's ListRuns RPC.
	RunServiceListRunsProcedure = "/agentcompose.v2.RunService/ListRuns"
	// RunServiceFollowRunLogsProcedure is the fully-qualified name of the RunService's FollowRunLogs
	// RPC.
	RunServiceFollowRunLogsProcedure = "/agentcompose.v2.RunService/FollowRunLogs"
	// RunServiceStopRunProcedure is the fully-qualified name of the RunService's StopRun RPC.
	RunServiceStopRunProcedure = "/agentcompose.v2.RunService/StopRun"
	// ExecServiceExecProcedure is the fully-qualified name of the ExecService's Exec RPC.
	ExecServiceExecProcedure = "/agentcompose.v2.ExecService/Exec"
	// ExecServiceExecStreamProcedure is the fully-qualified name of the ExecService's ExecStream RPC.
	ExecServiceExecStreamProcedure = "/agentcompose.v2.ExecService/ExecStream"
	// ImageServiceListImagesProcedure is the fully-qualified name of the ImageService's ListImages RPC.
	ImageServiceListImagesProcedure = "/agentcompose.v2.ImageService/ListImages"
	// ImageServicePullImageProcedure is the fully-qualified name of the ImageService's PullImage RPC.
	ImageServicePullImageProcedure = "/agentcompose.v2.ImageService/PullImage"
	// ImageServiceInspectImageProcedure is the fully-qualified name of the ImageService's InspectImage
	// RPC.
	ImageServiceInspectImageProcedure = "/agentcompose.v2.ImageService/InspectImage"
	// ImageServiceRemoveImageProcedure is the fully-qualified name of the ImageService's RemoveImage
	// RPC.
	ImageServiceRemoveImageProcedure = "/agentcompose.v2.ImageService/RemoveImage"
	// SandboxServiceRemoveSandboxProcedure is the fully-qualified name of the SandboxService's
	// RemoveSandbox RPC.
	SandboxServiceRemoveSandboxProcedure = "/agentcompose.v2.SandboxService/RemoveSandbox"
	// SandboxServiceGetSandboxStatsProcedure is the fully-qualified name of the SandboxService's
	// GetSandboxStats RPC.
	SandboxServiceGetSandboxStatsProcedure = "/agentcompose.v2.SandboxService/GetSandboxStats"
)

// ProjectServiceClient is a client for the agentcompose.v2.ProjectService service.
type ProjectServiceClient interface {
	ValidateProject(context.Context, *connect.Request[v2.ValidateProjectRequest]) (*connect.Response[v2.ValidateProjectResponse], error)
	ApplyProject(context.Context, *connect.Request[v2.ApplyProjectRequest]) (*connect.Response[v2.ApplyProjectResponse], error)
	GetProject(context.Context, *connect.Request[v2.GetProjectRequest]) (*connect.Response[v2.GetProjectResponse], error)
	ListProjects(context.Context, *connect.Request[v2.ListProjectsRequest]) (*connect.Response[v2.ListProjectsResponse], error)
	RemoveProject(context.Context, *connect.Request[v2.RemoveProjectRequest]) (*connect.Response[v2.RemoveProjectResponse], error)
	WatchProject(context.Context, *connect.Request[v2.WatchProjectRequest]) (*connect.ServerStreamForClient[v2.WatchProjectResponse], error)
}

// NewProjectServiceClient constructs a client for the agentcompose.v2.ProjectService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProjectServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProjectServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	projectServiceMethods := v2.File_proto_agentcompose_v2_agentcompose_proto.Services().ByName("ProjectService").Methods()
	return &projectServiceClient{
		validateProject: connect.NewClient[v2.ValidateProjectRequest, v2.ValidateProjectResponse](
			httpClient,
			baseURL+ProjectServiceValidateProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ValidateProject")),
			connect.WithClientOptions(opts...),
		),
		applyProject: connect.NewClient[v2.ApplyProjectRequest, v2.ApplyProjectResponse](
			httpClient,
			baseURL+ProjectServiceApplyProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ApplyProject")),
			connect.WithClientOptions(opts...),
		),
		getProject: connect.NewClient[v2.GetProjectRequest, v2.GetProjectResponse](
			httpClient,
			baseURL+ProjectServiceGetProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("GetProject")),
			connect.WithClientOptions(opts...),
		),
		listProjects: connect.NewClient[v2.ListProjectsRequest, v2.ListProjectsResponse](
			httpClient,
			baseURL+ProjectServiceListProjectsProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ListProjects")),
			connect.WithClientOptions(opts...),
		),
		removeProject: connect.NewClient[v2.RemoveProjectRequest, v2.RemoveProjectResponse](
			httpClient,
			baseURL+ProjectServiceRemoveProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("RemoveProject")),
			connect.WithClientOptions(opts...),
		),
		watchProject: connect.NewClient[v2.WatchProjectRequest, v2.WatchProjectResponse](
			httpClient,
			baseURL+ProjectServiceWatchProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("WatchProject")),
			connect.WithClientOptions(opts...),
		),
	}
}

// projectServiceClient implements ProjectServiceClient.
type projectServiceClient struct {
	validateProject *connect.Client[v2.ValidateProjectRequest, v2.ValidateProjectResponse]
	applyProject    *connect.Client[v2.ApplyProjectRequest, v2.ApplyProjectResponse]
	getProject      *connect.Client[v2.GetProjectRequest, v2.GetProjectResponse]
	listProjects    *connect.Client[v2.ListProjectsRequest, v2.ListProjectsResponse]
	removeProject   *connect.Client[v2.RemoveProjectRequest, v2.RemoveProjectResponse]
	watchProject    *connect.Client[v2.WatchProjectRequest, v2.WatchProjectResponse]
}

// ValidateProject calls agentcompose.v2.ProjectService.ValidateProject.
func (c *projectServiceClient) ValidateProject(ctx context.Context, req *connect.Request[v2.ValidateProjectRequest]) (*connect.Response[v2.ValidateProjectResponse], error) {
	return c.validateProject.CallUnary(ctx, req)
}

// ApplyProject calls agentcompose.v2.ProjectService.ApplyProject.
func (c *projectServiceClient) ApplyProject(ctx context.Context, req *connect.Request[v2.ApplyProjectRequest]) (*connect.Response[v2.ApplyProjectResponse], error) {
	return c.applyProject.CallUnary(ctx, req)
}

// GetProject calls agentcompose.v2.ProjectService.GetProject.
func (c *projectServiceClient) GetProject(ctx context.Context, req *connect.Request[v2.GetProjectRequest]) (*connect.Response[v2.GetProjectResponse], error) {
	return c.getProject.CallUnary(ctx, req)
}

// ListProjects calls agentcompose.v2.ProjectService.ListProjects.
func (c *projectServiceClient) ListProjects(ctx context.Context, req *connect.Request[v2.ListProjectsRequest]) (*connect.Response[v2.ListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// RemoveProject calls agentcompose.v2.ProjectService.RemoveProject.
func (c *projectServiceClient) RemoveProject(ctx context.Context, req *connect.Request[v2.RemoveProjectRequest]) (*connect.Response[v2.RemoveProjectResponse], error) {
	return c.removeProject.CallUnary(ctx, req)
}

// WatchProject calls agentcompose.v2.ProjectService.WatchProject.
func (c *projectServiceClient) WatchProject(ctx context.Context, req *connect.Request[v2.WatchProjectRequest]) (*connect.ServerStreamForClient[v2.WatchProjectResponse], error) {
	return c.watchProject.CallServerStream(ctx, req)
}

// ProjectServiceHandler is an implementation of the agentcompose.v2.ProjectService service.
type ProjectServiceHandler interface {
	ValidateProject(context.Context, *connect.Request[v2.ValidateProjectRequest]) (*connect.Response[v2.ValidateProjectResponse], error)
	ApplyProject(context.Context, *connect.Request[v2.ApplyProjectRequest]) (*connect.Response[v2.ApplyProjectResponse], error)
	GetProject(context.Context, *connect.Request[v2.GetProjectRequest]) (*connect.Response[v2.GetProjectResponse], error)
	ListProjects(context.Context, *connect.Request[v2.ListProjectsRequest]) (*connect.Response[v2.ListProjectsResponse], error)
	RemoveProject(context.Context, *connect.Request[v2.RemoveProjectRequest]) (*connect.Response[v2.RemoveProjectResponse], error)
	WatchProject(context.Context, *connect.Request[v2.WatchProjectRequest], *connect.ServerStream[v2.WatchProjectResponse]) error
}

// NewProjectServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProjectServiceHandler(svc ProjectServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	projectServiceMethods := v2.File_proto_agentcompose_v2_agentcompose_proto.Services().ByName("ProjectService").Methods()
	projectServiceValidateProjectHandler := connect.NewUnaryHandler(
		ProjectServiceValidateProjectProcedure,
		svc.ValidateProject,
		connect.WithSchema(projectServiceMethods.ByName("ValidateProject")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceApplyProjectHandler := connect.NewUnaryHandler(
		ProjectServiceApplyProjectProcedure,
		svc.ApplyProject,
		connect.WithSchema(projectServiceMethods.ByName("ApplyProject")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceGetProjectHandler := connect.NewUnaryHandler(
		ProjectServiceGetProjectProcedure,
		svc.GetProject,
		connect.WithSchema(projectServiceMethods.ByName("GetProject")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceListProjectsHandler := connect.NewUnaryHandler(
		ProjectServiceListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(projectServiceMethods.ByName("ListProjects")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceRemoveProjectHandler := connect.NewUnaryHandler(
		ProjectServiceRemoveProjectProcedure,
		svc.RemoveProject,
		connect.WithSchema(projectServiceMethods.ByName("RemoveProject")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceWatchProjectHandler := connect.NewServerStreamHandler(
		ProjectServiceWatchProjectProcedure,
		svc.WatchProject,
		connect.WithSchema(projectServiceMethods.ByName("WatchProject")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agentcompose.v2.ProjectService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProjectServiceValidateProjectProcedure:
			projectServiceValidateProjectHandler.ServeHTTP(w, r)
		case ProjectServiceApplyProjectProcedure:
			projectServiceApplyProjectHandler.ServeHTTP(w, r)
		case ProjectServiceGetProjectProcedure:
			projectServiceGetProjectHandler.ServeHTTP(w, r)
		case ProjectServiceListProjectsProcedure:
			projectServiceListProjectsHandler.ServeHTTP(w, r)
		case ProjectServiceRemoveProjectProcedure:
			projectServiceRemoveProjectHandler.ServeHTTP(w, r)
		case ProjectServiceWatchProjectProcedure:
			projectServiceWatchProjectHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProjectServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProjectServiceHandler struct{}

func (UnimplementedProjectServiceHandler) ValidateProject(context.Context, *connect.Request[v2.ValidateProjectRequest]) (*connect.Response[v2.ValidateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ProjectService.ValidateProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) ApplyProject(context.Context, *connect.Request[v2.ApplyProjectRequest]) (*connect.Response[v2.ApplyProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ProjectService.ApplyProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) GetProject(context.Context, *connect.Request[v2.GetProjectRequest]) (*connect.Response[v2.GetProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ProjectService.GetProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) ListProjects(context.Context, *connect.Request[v2.ListProjectsRequest]) (*connect.Response[v2.ListProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ProjectService.ListProjects is not implemented"))
}

func (UnimplementedProjectServiceHandler) RemoveProject(context.Context, *connect.Request[v2.RemoveProjectRequest]) (*connect.Response[v2.RemoveProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ProjectService.RemoveProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) WatchProject(context.Context, *connect.Request[v2.WatchProjectRequest], *connect.ServerStream[v2.WatchProjectResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ProjectService.WatchProject is not implemented"))
}

// RunServiceClient is a client for the agentcompose.v2.RunService service.
type RunServiceClient interface {
	RunAgent(context.Context, *connect.Request[v2.RunAgentRequest]) (*connect.Response[v2.RunAgentResponse], error)
	StartRun(context.Context, *connect.Request[v2.StartRunRequest]) (*connect.Response[v2.StartRunResponse], error)
	RunAgentStream(context.Context, *connect.Request[v2.RunAgentRequest]) (*connect.ServerStreamForClient[v2.RunAgentStreamResponse], error)
	GetRun(context.Context, *connect.Request[v2.GetRunRequest]) (*connect.Response[v2.GetRunResponse], error)
	ListRuns(context.Context, *connect.Request[v2.ListRunsRequest]) (*connect.Response[v2.ListRunsResponse], error)
	FollowRunLogs(context.Context, *connect.Request[v2.FollowRunLogsRequest]) (*connect.ServerStreamForClient[v2.RunLogChunk], error)
	StopRun(context.Context, *connect.Request[v2.StopRunRequest]) (*connect.Response[v2.StopRunResponse], error)
}

// NewRunServiceClient constructs a client for the agentcompose.v2.RunService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRunServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RunServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	runServiceMethods := v2.File_proto_agentcompose_v2_agentcompose_proto.Services().ByName("RunService").Methods()
	return &runServiceClient{
		runAgent: connect.NewClient[v2.RunAgentRequest, v2.RunAgentResponse](
			httpClient,
			baseURL+RunServiceRunAgentProcedure,
			connect.WithSchema(runServiceMethods.ByName("RunAgent")),
			connect.WithClientOptions(opts...),
		),
		startRun: connect.NewClient[v2.StartRunRequest, v2.StartRunResponse](
			httpClient,
			baseURL+RunServiceStartRunProcedure,
			connect.WithSchema(runServiceMethods.ByName("StartRun")),
			connect.WithClientOptions(opts...),
		),
		runAgentStream: connect.NewClient[v2.RunAgentRequest, v2.RunAgentStreamResponse](
			httpClient,
			baseURL+RunServiceRunAgentStreamProcedure,
			connect.WithSchema(runServiceMethods.ByName("RunAgentStream")),
			connect.WithClientOptions(opts...),
		),
		getRun: connect.NewClient[v2.GetRunRequest, v2.GetRunResponse](
			httpClient,
			baseURL+RunServiceGetRunProcedure,
			connect.WithSchema(runServiceMethods.ByName("GetRun")),
			connect.WithClientOptions(opts...),
		),
		listRuns: connect.NewClient[v2.ListRunsRequest, v2.ListRunsResponse](
			httpClient,
			baseURL+RunServiceListRunsProcedure,
			connect.WithSchema(runServiceMethods.ByName("ListRuns")),
			connect.WithClientOptions(opts...),
		),
		followRunLogs: connect.NewClient[v2.FollowRunLogsRequest, v2.RunLogChunk](
			httpClient,
			baseURL+RunServiceFollowRunLogsProcedure,
			connect.WithSchema(runServiceMethods.ByName("FollowRunLogs")),
			connect.WithClientOptions(opts...),
		),
		stopRun: connect.NewClient[v2.StopRunRequest, v2.StopRunResponse](
			httpClient,
			baseURL+RunServiceStopRunProcedure,
			connect.WithSchema(runServiceMethods.ByName("StopRun")),
			connect.WithClientOptions(opts...),
		),
	}
}

// runServiceClient implements RunServiceClient.
type runServiceClient struct {
	runAgent       *connect.Client[v2.RunAgentRequest, v2.RunAgentResponse]
	startRun       *connect.Client[v2.StartRunRequest, v2.StartRunResponse]
	runAgentStream *connect.Client[v2.RunAgentRequest, v2.RunAgentStreamResponse]
	getRun         *connect.Client[v2.GetRunRequest, v2.GetRunResponse]
	listRuns       *connect.Client[v2.ListRunsRequest, v2.ListRunsResponse]
	followRunLogs  *connect.Client[v2.FollowRunLogsRequest, v2.RunLogChunk]
	stopRun        *connect.Client[v2.StopRunRequest, v2.StopRunResponse]
}

// RunAgent calls agentcompose.v2.RunService.RunAgent.
func (c *runServiceClient) RunAgent(ctx context.Context, req *connect.Request[v2.RunAgentRequest]) (*connect.Response[v2.RunAgentResponse], error) {
	return c.runAgent.CallUnary(ctx, req)
}

// StartRun calls agentcompose.v2.RunService.StartRun.
func (c *runServiceClient) StartRun(ctx context.Context, req *connect.Request[v2.StartRunRequest]) (*connect.Response[v2.StartRunResponse], error) {
	return c.startRun.CallUnary(ctx, req)
}

// RunAgentStream calls agentcompose.v2.RunService.RunAgentStream.
func (c *runServiceClient) RunAgentStream(ctx context.Context, req *connect.Request[v2.RunAgentRequest]) (*connect.ServerStreamForClient[v2.RunAgentStreamResponse], error) {
	return c.runAgentStream.CallServerStream(ctx, req)
}

// GetRun calls agentcompose.v2.RunService.GetRun.
func (c *runServiceClient) GetRun(ctx context.Context, req *connect.Request[v2.GetRunRequest]) (*connect.Response[v2.GetRunResponse], error) {
	return c.getRun.CallUnary(ctx, req)
}

// ListRuns calls agentcompose.v2.RunService.ListRuns.
func (c *runServiceClient) ListRuns(ctx context.Context, req *connect.Request[v2.ListRunsRequest]) (*connect.Response[v2.ListRunsResponse], error) {
	return c.listRuns.CallUnary(ctx, req)
}

// FollowRunLogs calls agentcompose.v2.RunService.FollowRunLogs.
func (c *runServiceClient) FollowRunLogs(ctx context.Context, req *connect.Request[v2.FollowRunLogsRequest]) (*connect.ServerStreamForClient[v2.RunLogChunk], error) {
	return c.followRunLogs.CallServerStream(ctx, req)
}

// StopRun calls agentcompose.v2.RunService.StopRun.
func (c *runServiceClient) StopRun(ctx context.Context, req *connect.Request[v2.StopRunRequest]) (*connect.Response[v2.StopRunResponse], error) {
	return c.stopRun.CallUnary(ctx, req)
}

// RunServiceHandler is an implementation of the agentcompose.v2.RunService service.
type RunServiceHandler interface {
	RunAgent(context.Context, *connect.Request[v2.RunAgentRequest]) (*connect.Response[v2.RunAgentResponse], error)
	StartRun(context.Context, *connect.Request[v2.StartRunRequest]) (*connect.Response[v2.StartRunResponse], error)
	RunAgentStream(context.Context, *connect.Request[v2.RunAgentRequest], *connect.ServerStream[v2.RunAgentStreamResponse]) error
	GetRun(context.Context, *connect.Request[v2.GetRunRequest]) (*connect.Response[v2.GetRunResponse], error)
	ListRuns(context.Context, *connect.Request[v2.ListRunsRequest]) (*connect.Response[v2.ListRunsResponse], error)
	FollowRunLogs(context.Context, *connect.Request[v2.FollowRunLogsRequest], *connect.ServerStream[v2.RunLogChunk]) error
	StopRun(context.Context, *connect.Request[v2.StopRunRequest]) (*connect.Response[v2.StopRunResponse], error)
}

// NewRunServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRunServiceHandler(svc RunServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	runServiceMethods := v2.File_proto_agentcompose_v2_agentcompose_proto.Services().ByName("RunService").Methods()
	runServiceRunAgentHandler := connect.NewUnaryHandler(
		RunServiceRunAgentProcedure,
		svc.RunAgent,
		connect.WithSchema(runServiceMethods.ByName("RunAgent")),
		connect.WithHandlerOptions(opts...),
	)
	runServiceStartRunHandler := connect.NewUnaryHandler(
		RunServiceStartRunProcedure,
		svc.StartRun,
		connect.WithSchema(runServiceMethods.ByName("StartRun")),
		connect.WithHandlerOptions(opts...),
	)
	runServiceRunAgentStreamHandler := connect.NewServerStreamHandler(
		RunServiceRunAgentStreamProcedure,
		svc.RunAgentStream,
		connect.WithSchema(runServiceMethods.ByName("RunAgentStream")),
		connect.WithHandlerOptions(opts...),
	)
	runServiceGetRunHandler := connect.NewUnaryHandler(
		RunServiceGetRunProcedure,
		svc.GetRun,
		connect.WithSchema(runServiceMethods.ByName("GetRun")),
		connect.WithHandlerOptions(opts...),
	)
	runServiceListRunsHandler := connect.NewUnaryHandler(
		RunServiceListRunsProcedure,
		svc.ListRuns,
		connect.WithSchema(runServiceMethods.ByName("ListRuns")),
		connect.WithHandlerOptions(opts...),
	)
	runServiceFollowRunLogsHandler := connect.NewServerStreamHandler(
		RunServiceFollowRunLogsProcedure,
		svc.FollowRunLogs,
		connect.WithSchema(runServiceMethods.ByName("FollowRunLogs")),
		connect.WithHandlerOptions(opts...),
	)
	runServiceStopRunHandler := connect.NewUnaryHandler(
		RunServiceStopRunProcedure,
		svc.StopRun,
		connect.WithSchema(runServiceMethods.ByName("StopRun")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agentcompose.v2.RunService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RunServiceRunAgentProcedure:
			runServiceRunAgentHandler.ServeHTTP(w, r)
		case RunServiceStartRunProcedure:
			runServiceStartRunHandler.ServeHTTP(w, r)
		case RunServiceRunAgentStreamProcedure:
			runServiceRunAgentStreamHandler.ServeHTTP(w, r)
		case RunServiceGetRunProcedure:
			runServiceGetRunHandler.ServeHTTP(w, r)
		case RunServiceListRunsProcedure:
			runServiceListRunsHandler.ServeHTTP(w, r)
		case RunServiceFollowRunLogsProcedure:
			runServiceFollowRunLogsHandler.ServeHTTP(w, r)
		case RunServiceStopRunProcedure:
			runServiceStopRunHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRunServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRunServiceHandler struct{}

func (UnimplementedRunServiceHandler) RunAgent(context.Context, *connect.Request[v2.RunAgentRequest]) (*connect.Response[v2.RunAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.RunService.RunAgent is not implemented"))
}

func (UnimplementedRunServiceHandler) StartRun(context.Context, *connect.Request[v2.StartRunRequest]) (*connect.Response[v2.StartRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.RunService.StartRun is not implemented"))
}

func (UnimplementedRunServiceHandler) RunAgentStream(context.Context, *connect.Request[v2.RunAgentRequest], *connect.ServerStream[v2.RunAgentStreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.RunService.RunAgentStream is not implemented"))
}

func (UnimplementedRunServiceHandler) GetRun(context.Context, *connect.Request[v2.GetRunRequest]) (*connect.Response[v2.GetRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.RunService.GetRun is not implemented"))
}

func (UnimplementedRunServiceHandler) ListRuns(context.Context, *connect.Request[v2.ListRunsRequest]) (*connect.Response[v2.ListRunsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.RunService.ListRuns is not implemented"))
}

func (UnimplementedRunServiceHandler) FollowRunLogs(context.Context, *connect.Request[v2.FollowRunLogsRequest], *connect.ServerStream[v2.RunLogChunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.RunService.FollowRunLogs is not implemented"))
}

func (UnimplementedRunServiceHandler) StopRun(context.Context, *connect.Request[v2.StopRunRequest]) (*connect.Response[v2.StopRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.RunService.StopRun is not implemented"))
}

// ExecServiceClient is a client for the agentcompose.v2.ExecService service.
type ExecServiceClient interface {
	Exec(context.Context, *connect.Request[v2.ExecRequest]) (*connect.Response[v2.ExecResponse], error)
	ExecStream(context.Context, *connect.Request[v2.ExecRequest]) (*connect.ServerStreamForClient[v2.ExecStreamResponse], error)
}

// NewExecServiceClient constructs a client for the agentcompose.v2.ExecService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewExecServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ExecServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	execServiceMethods := v2.File_proto_agentcompose_v2_agentcompose_proto.Services().ByName("ExecService").Methods()
	return &execServiceClient{
		exec: connect.NewClient[v2.ExecRequest, v2.ExecResponse](
			httpClient,
			baseURL+ExecServiceExecProcedure,
			connect.WithSchema(execServiceMethods.ByName("Exec")),
			connect.WithClientOptions(opts...),
		),
		execStream: connect.NewClient[v2.ExecRequest, v2.ExecStreamResponse](
			httpClient,
			baseURL+ExecServiceExecStreamProcedure,
			connect.WithSchema(execServiceMethods.ByName("ExecStream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// execServiceClient implements ExecServiceClient.
type execServiceClient struct {
	exec       *connect.Client[v2.ExecRequest, v2.ExecResponse]
	execStream *connect.Client[v2.ExecRequest, v2.ExecStreamResponse]
}

// Exec calls agentcompose.v2.ExecService.Exec.
func (c *execServiceClient) Exec(ctx context.Context, req *connect.Request[v2.ExecRequest]) (*connect.Response[v2.ExecResponse], error) {
	return c.exec.CallUnary(ctx, req)
}

// ExecStream calls agentcompose.v2.ExecService.ExecStream.
func (c *execServiceClient) ExecStream(ctx context.Context, req *connect.Request[v2.ExecRequest]) (*connect.ServerStreamForClient[v2.ExecStreamResponse], error) {
	return c.execStream.CallServerStream(ctx, req)
}

// ExecServiceHandler is an implementation of the agentcompose.v2.ExecService service.
type ExecServiceHandler interface {
	Exec(context.Context, *connect.Request[v2.ExecRequest]) (*connect.Response[v2.ExecResponse], error)
	ExecStream(context.Context, *connect.Request[v2.ExecRequest], *connect.ServerStream[v2.ExecStreamResponse]) error
}

// NewExecServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewExecServiceHandler(svc ExecServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	execServiceMethods := v2.File_proto_agentcompose_v2_agentcompose_proto.Services().ByName("ExecService").Methods()
	execServiceExecHandler := connect.NewUnaryHandler(
		ExecServiceExecProcedure,
		svc.Exec,
		connect.WithSchema(execServiceMethods.ByName("Exec")),
		connect.WithHandlerOptions(opts...),
	)
	execServiceExecStreamHandler := connect.NewServerStreamHandler(
		ExecServiceExecStreamProcedure,
		svc.ExecStream,
		connect.WithSchema(execServiceMethods.ByName("ExecStream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agentcompose.v2.ExecService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ExecServiceExecProcedure:
			execServiceExecHandler.ServeHTTP(w, r)
		case ExecServiceExecStreamProcedure:
			execServiceExecStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedExecServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedExecServiceHandler struct{}

func (UnimplementedExecServiceHandler) Exec(context.Context, *connect.Request[v2.ExecRequest]) (*connect.Response[v2.ExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ExecService.Exec is not implemented"))
}

func (UnimplementedExecServiceHandler) ExecStream(context.Context, *connect.Request[v2.ExecRequest], *connect.ServerStream[v2.ExecStreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ExecService.ExecStream is not implemented"))
}

// ImageServiceClient is a client for the agentcompose.v2.ImageService service.
type ImageServiceClient interface {
	ListImages(context.Context, *connect.Request[v2.ListImagesRequest]) (*connect.Response[v2.ListImagesResponse], error)
	PullImage(context.Context, *connect.Request[v2.PullImageRequest]) (*connect.Response[v2.PullImageResponse], error)
	InspectImage(context.Context, *connect.Request[v2.InspectImageRequest]) (*connect.Response[v2.InspectImageResponse], error)
	RemoveImage(context.Context, *connect.Request[v2.RemoveImageRequest]) (*connect.Response[v2.RemoveImageResponse], error)
}

// NewImageServiceClient constructs a client for the agentcompose.v2.ImageService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewImageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ImageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	imageServiceMethods := v2.File_proto_agentcompose_v2_agentcompose_proto.Services().ByName("ImageService").Methods()
	return &imageServiceClient{
		listImages: connect.NewClient[v2.ListImagesRequest, v2.ListImagesResponse](
			httpClient,
			baseURL+ImageServiceListImagesProcedure,
			connect.WithSchema(imageServiceMethods.ByName("ListImages")),
			connect.WithClientOptions(opts...),
		),
		pullImage: connect.NewClient[v2.PullImageRequest, v2.PullImageResponse](
			httpClient,
			baseURL+ImageServicePullImageProcedure,
			connect.WithSchema(imageServiceMethods.ByName("PullImage")),
			connect.WithClientOptions(opts...),
		),
		inspectImage: connect.NewClient[v2.InspectImageRequest, v2.InspectImageResponse](
			httpClient,
			baseURL+ImageServiceInspectImageProcedure,
			connect.WithSchema(imageServiceMethods.ByName("InspectImage")),
			connect.WithClientOptions(opts...),
		),
		removeImage: connect.NewClient[v2.RemoveImageRequest, v2.RemoveImageResponse](
			httpClient,
			baseURL+ImageServiceRemoveImageProcedure,
			connect.WithSchema(imageServiceMethods.ByName("RemoveImage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// imageServiceClient implements ImageServiceClient.
type imageServiceClient struct {
	listImages   *connect.Client[v2.ListImagesRequest, v2.ListImagesResponse]
	pullImage    *connect.Client[v2.PullImageRequest, v2.PullImageResponse]
	inspectImage *connect.Client[v2.InspectImageRequest, v2.InspectImageResponse]
	removeImage  *connect.Client[v2.RemoveImageRequest, v2.RemoveImageResponse]
}

// ListImages calls agentcompose.v2.ImageService.ListImages.
func (c *imageServiceClient) ListImages(ctx context.Context, req *connect.Request[v2.ListImagesRequest]) (*connect.Response[v2.ListImagesResponse], error) {
	return c.listImages.CallUnary(ctx, req)
}

// PullImage calls agentcompose.v2.ImageService.PullImage.
func (c *imageServiceClient) PullImage(ctx context.Context, req *connect.Request[v2.PullImageRequest]) (*connect.Response[v2.PullImageResponse], error) {
	return c.pullImage.CallUnary(ctx, req)
}

// InspectImage calls agentcompose.v2.ImageService.InspectImage.
func (c *imageServiceClient) InspectImage(ctx context.Context, req *connect.Request[v2.InspectImageRequest]) (*connect.Response[v2.InspectImageResponse], error) {
	return c.inspectImage.CallUnary(ctx, req)
}

// RemoveImage calls agentcompose.v2.ImageService.RemoveImage.
func (c *imageServiceClient) RemoveImage(ctx context.Context, req *connect.Request[v2.RemoveImageRequest]) (*connect.Response[v2.RemoveImageResponse], error) {
	return c.removeImage.CallUnary(ctx, req)
}

// ImageServiceHandler is an implementation of the agentcompose.v2.ImageService service.
type ImageServiceHandler interface {
	ListImages(context.Context, *connect.Request[v2.ListImagesRequest]) (*connect.Response[v2.ListImagesResponse], error)
	PullImage(context.Context, *connect.Request[v2.PullImageRequest]) (*connect.Response[v2.PullImageResponse], error)
	InspectImage(context.Context, *connect.Request[v2.InspectImageRequest]) (*connect.Response[v2.InspectImageResponse], error)
	RemoveImage(context.Context, *connect.Request[v2.RemoveImageRequest]) (*connect.Response[v2.RemoveImageResponse], error)
}

// NewImageServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewImageServiceHandler(svc ImageServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	imageServiceMethods := v2.File_proto_agentcompose_v2_agentcompose_proto.Services().ByName("ImageService").Methods()
	imageServiceListImagesHandler := connect.NewUnaryHandler(
		ImageServiceListImagesProcedure,
		svc.ListImages,
		connect.WithSchema(imageServiceMethods.ByName("ListImages")),
		connect.WithHandlerOptions(opts...),
	)
	imageServicePullImageHandler := connect.NewUnaryHandler(
		ImageServicePullImageProcedure,
		svc.PullImage,
		connect.WithSchema(imageServiceMethods.ByName("PullImage")),
		connect.WithHandlerOptions(opts...),
	)
	imageServiceInspectImageHandler := connect.NewUnaryHandler(
		ImageServiceInspectImageProcedure,
		svc.InspectImage,
		connect.WithSchema(imageServiceMethods.ByName("InspectImage")),
		connect.WithHandlerOptions(opts...),
	)
	imageServiceRemoveImageHandler := connect.NewUnaryHandler(
		ImageServiceRemoveImageProcedure,
		svc.RemoveImage,
		connect.WithSchema(imageServiceMethods.ByName("RemoveImage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agentcompose.v2.ImageService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ImageServiceListImagesProcedure:
			imageServiceListImagesHandler.ServeHTTP(w, r)
		case ImageServicePullImageProcedure:
			imageServicePullImageHandler.ServeHTTP(w, r)
		case ImageServiceInspectImageProcedure:
			imageServiceInspectImageHandler.ServeHTTP(w, r)
		case ImageServiceRemoveImageProcedure:
			imageServiceRemoveImageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedImageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedImageServiceHandler struct{}

func (UnimplementedImageServiceHandler) ListImages(context.Context, *connect.Request[v2.ListImagesRequest]) (*connect.Response[v2.ListImagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ImageService.ListImages is not implemented"))
}

func (UnimplementedImageServiceHandler) PullImage(context.Context, *connect.Request[v2.PullImageRequest]) (*connect.Response[v2.PullImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ImageService.PullImage is not implemented"))
}

func (UnimplementedImageServiceHandler) InspectImage(context.Context, *connect.Request[v2.InspectImageRequest]) (*connect.Response[v2.InspectImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ImageService.InspectImage is not implemented"))
}

func (UnimplementedImageServiceHandler) RemoveImage(context.Context, *connect.Request[v2.RemoveImageRequest]) (*connect.Response[v2.RemoveImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.ImageService.RemoveImage is not implemented"))
}

// SandboxServiceClient is a client for the agentcompose.v2.SandboxService service.
type SandboxServiceClient interface {
	RemoveSandbox(context.Context, *connect.Request[v2.RemoveSandboxRequest]) (*connect.Response[v2.RemoveSandboxResponse], error)
	GetSandboxStats(context.Context, *connect.Request[v2.GetSandboxStatsRequest]) (*connect.Response[v2.GetSandboxStatsResponse], error)
}

// NewSandboxServiceClient constructs a client for the agentcompose.v2.SandboxService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSandboxServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SandboxServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sandboxServiceMethods := v2.File_proto_agentcompose_v2_agentcompose_proto.Services().ByName("SandboxService").Methods()
	return &sandboxServiceClient{
		removeSandbox: connect.NewClient[v2.RemoveSandboxRequest, v2.RemoveSandboxResponse](
			httpClient,
			baseURL+SandboxServiceRemoveSandboxProcedure,
			connect.WithSchema(sandboxServiceMethods.ByName("RemoveSandbox")),
			connect.WithClientOptions(opts...),
		),
		getSandboxStats: connect.NewClient[v2.GetSandboxStatsRequest, v2.GetSandboxStatsResponse](
			httpClient,
			baseURL+SandboxServiceGetSandboxStatsProcedure,
			connect.WithSchema(sandboxServiceMethods.ByName("GetSandboxStats")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sandboxServiceClient implements SandboxServiceClient.
type sandboxServiceClient struct {
	removeSandbox   *connect.Client[v2.RemoveSandboxRequest, v2.RemoveSandboxResponse]
	getSandboxStats *connect.Client[v2.GetSandboxStatsRequest, v2.GetSandboxStatsResponse]
}

// RemoveSandbox calls agentcompose.v2.SandboxService.RemoveSandbox.
func (c *sandboxServiceClient) RemoveSandbox(ctx context.Context, req *connect.Request[v2.RemoveSandboxRequest]) (*connect.Response[v2.RemoveSandboxResponse], error) {
	return c.removeSandbox.CallUnary(ctx, req)
}

// GetSandboxStats calls agentcompose.v2.SandboxService.GetSandboxStats.
func (c *sandboxServiceClient) GetSandboxStats(ctx context.Context, req *connect.Request[v2.GetSandboxStatsRequest]) (*connect.Response[v2.GetSandboxStatsResponse], error) {
	return c.getSandboxStats.CallUnary(ctx, req)
}

// SandboxServiceHandler is an implementation of the agentcompose.v2.SandboxService service.
type SandboxServiceHandler interface {
	RemoveSandbox(context.Context, *connect.Request[v2.RemoveSandboxRequest]) (*connect.Response[v2.RemoveSandboxResponse], error)
	GetSandboxStats(context.Context, *connect.Request[v2.GetSandboxStatsRequest]) (*connect.Response[v2.GetSandboxStatsResponse], error)
}

// NewSandboxServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSandboxServiceHandler(svc SandboxServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sandboxServiceMethods := v2.File_proto_agentcompose_v2_agentcompose_proto.Services().ByName("SandboxService").Methods()
	sandboxServiceRemoveSandboxHandler := connect.NewUnaryHandler(
		SandboxServiceRemoveSandboxProcedure,
		svc.RemoveSandbox,
		connect.WithSchema(sandboxServiceMethods.ByName("RemoveSandbox")),
		connect.WithHandlerOptions(opts...),
	)
	sandboxServiceGetSandboxStatsHandler := connect.NewUnaryHandler(
		SandboxServiceGetSandboxStatsProcedure,
		svc.GetSandboxStats,
		connect.WithSchema(sandboxServiceMethods.ByName("GetSandboxStats")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agentcompose.v2.SandboxService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SandboxServiceRemoveSandboxProcedure:
			sandboxServiceRemoveSandboxHandler.ServeHTTP(w, r)
		case SandboxServiceGetSandboxStatsProcedure:
			sandboxServiceGetSandboxStatsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSandboxServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSandboxServiceHandler struct{}

func (UnimplementedSandboxServiceHandler) RemoveSandbox(context.Context, *connect.Request[v2.RemoveSandboxRequest]) (*connect.Response[v2.RemoveSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.SandboxService.RemoveSandbox is not implemented"))
}

func (UnimplementedSandboxServiceHandler) GetSandboxStats(context.Context, *connect.Request[v2.GetSandboxStatsRequest]) (*connect.Response[v2.GetSandboxStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agentcompose.v2.SandboxService.GetSandboxStats is not implemented"))
}
